version: "3.9"
services:
   frontend:
      build:
         context: ./frontend
         # dockerfile: Dockerfile
      ports:
         - 8080:3000
      environment:
         - API_URI=http://topics-api:5000/api/topics
      depends_on:
         - topics-api
      networks:
         - lemoncode-challenge
   topics-api:
      build:
         context: ./backend
      environment:
         - DATABASE_URL=mongodb://root:root@node-stack-mongodb-1:27017
         - DATABASE_NAME=TopicstoreDb
         - HOST=topics-api
      depends_on:
         - mongodb
      networks:
         - lemoncode-challenge
   mongodb:
      image: mongo:latest
      ports:
         - 27017:27017
      volumes:
         - mongo_data:/data/db
      environment:
         - MONGO_INITDB_ROOT_USERNAME=root
         - MONGO_INITDB_ROOT_PASSWORD=root
      networks:
         - lemoncode-challenge
volumes:
   mongo_data:
networks:
   lemoncode-challenge:
