pipeline {
    agent {
        docker {
            image 'gradle:6.6.1-jre14-openj9'
        }
    }

    stages {
        stage ('Compile') {
            steps {
                dir("$WORKSPACE/LaboratorioJenkins/jenkins-resources/calculator") {
                    sh '''
                    chmod +x gradlew
                    ./gradlew compileJava
                    '''
                }
            }
        }
        stage ('Unit Test') {
            steps {
                dir("$WORKSPACE/LaboratorioJenkins/jenkins-resources/calculator") {
                    sh './gradlew test'
                }
            }
        }
    }
}
