apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
  namespace: monolith
spec:
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo
        image: romandorosh/lc-todo-monolith-01
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: monolithcmapp
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: monolithcmapp
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: monolithcmbd
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: monolithcmbd
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: monolithcmbd
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: monolithcmbd
        - name: DB_VERSION
          valueFrom:
            configMapKeyRef:
              key: DB_VERSION
              name: monolithcmbd
       
        
