pipeline {
    agent any

    stages {
        stage ('Audit tools') {
            steps {
                sh '''
                    java -version
                    gradle -v
                '''
            }
        }
        stage ('demo-test') {
            steps {
                echo "Current directory is $PWD"
            }
        }
        stage ('Compile') {
            steps {
                dir('../jenkins-resources/calculator') {
                    sh './gradlew compileJava'
                }
            }
        }
        stage ('Unit Test') {
            steps {
                dir('../jenkins-resources/calculator') {
                    sh './gradlew test'
                }
            }
        }
    }
}
