pipeline {
    agent any

    stages {
        stage ('Audit tools') {
            steps {
                sh '''
                    java -version
                    gradle -v
                '''
            }
        }
        stage ('demo-test') {
            steps {
                dir('./calculator') {
                    echo "Files in current directory is $(ls)"
                }
                
            }
        }
        stage ('Compile') {
            steps {
                dir('./LaboratorioJenkins/jenkins-resources/calculator') {
                    sh './gradlew compileJava'
                }
            }
        }
        stage ('Unit Test') {
            steps {
                dir('../jenkins-resources/calculator') {
                    sh './gradlew test'
                }
            }
        }
    }
}
