pipeline {
    agent any

    stages {
        stage ('Audit tools') {
            steps {
                sh '''
                    java -version
                    gradle -v
                '''
            }
        }
        stage ('Compile') {
            steps {
                sh './gradlew compileJava'
            }
        }
        stage ('Unit Test') {
            steps {
                sh './gradlew test'
            }
        }
    }
}
