pipeline {
    agent any

    stages {
        stage ('Audit tools') {
            steps {
                sh '''
                    java -version
                    gradle -v
                '''
            }
        }
        stage ('Echo Test') {
            steps {
                echo "build number is ${BUILD_NUMBER}"
            }
        }
        stage ('Unit Test') {
            steps {
                sh 'gradlew test'
            }
        }
    }
}
